# Secrets

keys:
  - &erre age1za4x2kz9kuus40c5tfznckcy9vfrqzt6m0kclpr5q52lcx6fxywq2t9str
  - &superdator age1l9rlv0kltyh42f3t0hlmpulxkuez00dumw24w8ygw09497wea35q4ecgw8
  - &obsidian age1n2vym8aq3fdxrmpejz40pulnmwjhmw9u75xc8hrkvc98dq4h83jqkmlxug
  - &dunning age17jcxlfvqkva5ynsddfsnpk8wy99xjzmqwzc234ent49vvrgue9gsxncpwj
  - &kruger age1gqpyefghp8qlp9tw8s4q7yfglpqcr40tjm94d8t283jx6u0xrgksqksa9n
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *erre
        - *superdator
        - *obsidian
  - path_regex: secrets/ros2.yaml$
    key_groups:
      - age:
        - *erre
        - *obsidian
        - *dunning
        - *kruger

